### ISSUE TITLE
How to change the height and width of the inserted Imgur?

### ISSUE THREAD

**Issue by xinzhang-nac** [kaivalyar/Hugo-Imgur-Shortcode#1]
Hi kaivalyar,

Hope you can see this issue. I wonder whether we have a way to change the height and width of the inserted Imgur.

Thanks!

**Comment by kaivalyar** [comment]
I'm not sure how much styling imgur allows in their embedded iframes, if you wish to include a single image in your page the perhaps this shortcode is not really the right tool to use. The styling of imgure inserted iframes would probably require some more work, but an easy way to get some control might be to modify the ID wou're passing by appending a `s` for a small image, `ss` for extra small, etc. Alternatively, if you wish to control styles of the container div (I do not think this will change the size of the image rendered though, you're free to add styling information to the `imgur-image` class.
